<?php
/**
 * Pure-PHP smoke test for the AGENTS.md compose marker.
 *
 * Run: php tests/smoke-agents-md-marker.php
 *
 * Keeps the generated AGENTS.md marker aligned with the current memory
 * compose command surface.
 */

declare( strict_types=1 );

$failures = array();
$assert   = function ( string $label, bool $cond ) use ( &$failures ): void {
	if ( $cond ) {
		echo "  PASS {$label}\n";
		return;
	}

	$failures[] = $label;
	echo "  FAIL {$label}\n";
};

echo "AGENTS.md compose marker -- smoke\n";

$plugin_file = __DIR__ . '/../data-machine-code.php';
$source      = file_get_contents( $plugin_file );

$assert( 'plugin source is readable', is_string( $source ) && '' !== $source );

if ( ! is_string( $source ) ) {
	$source = '';
}

$expected_marker            = '<!-- regenerated by: {$wp} datamachine memory compose AGENTS.md -->';
$expected_description       = 'Regenerate via: wp datamachine memory compose AGENTS.md';
$stale_marker               = 'datamachine agent compose AGENTS.md';
$expected_agent_cli         = 'datamachine agent list|create|access|token|installed|install|diff';
$stale_agent_cli            = 'datamachine agents list|create|access|tokens';
$expected_worktree_cli      = 'datamachine-code workspace clone|worktree add|worktree list|worktree cleanup|worktree remove';
$expected_workspace_scan    = 'scans the workspace root for primary checkouts and `<repo>@<slug>` worktrees';
$expected_workspace_hygiene = 'worktree cleanup|cleanup-artifacts|reconcile-metadata|refresh-context';
$expected_code_task_cli     = 'datamachine-code code-task create';
$expected_gitsync_cli       = 'gitsync bind|status|pull|submit|push|policy';
$expected_homeboy_git       = 'homeboy changes | status';
$expected_homeboy_path      = '--path <checkout>';
$expected_homeboy_trace     = 'homeboy trace';
$expected_homeboy_review    = 'homeboy review --changed-since --report=pr-comment';
$stale_homeboy_git          = 'homeboy git changes';
$stale_workspace_registry   = 'keeps the on-disk registry consistent';

$assert(
	'auto-generated marker uses memory compose command',
	str_contains( $source, $expected_marker )
);
$assert(
	'MemoryFileRegistry description uses memory compose command',
	str_contains( $source, $expected_description )
);
$assert(
	'stale agent compose command is absent',
	! str_contains( $source, $stale_marker )
);
$assert(
	'agent CLI guidance uses current singular command surface',
	str_contains( $source, $expected_agent_cli )
);
$assert(
	'stale plural agent token guidance is absent',
	! str_contains( $source, $stale_agent_cli )
);
$assert(
	'workspace lifecycle guidance includes cleanup command',
	str_contains( $source, $expected_worktree_cli )
);
$assert(
	'workspace guidance describes scanned checkouts instead of a primary registry',
	str_contains( $source, $expected_workspace_scan )
);
$assert(
	'stale workspace registry wording is absent',
	! str_contains( $source, $stale_workspace_registry )
);
$assert(
	'workspace hygiene guidance includes modern maintenance surfaces',
	str_contains( $source, $expected_workspace_hygiene )
);
$assert(
	'code-task guidance includes create command',
	str_contains( $source, $expected_code_task_cli )
);
$assert(
	'GitSync guidance distinguishes compact sync family',
	str_contains( $source, $expected_gitsync_cli )
);
$assert(
	'Homeboy guidance uses top-level changes command',
	str_contains( $source, $expected_homeboy_git )
);
$assert(
	'Homeboy guidance covers --path checkout override',
	str_contains( $source, $expected_homeboy_path )
);
$assert(
	'Homeboy guidance includes trace surface',
	str_contains( $source, $expected_homeboy_trace )
);
$assert(
	'Homeboy guidance includes PR-style review loop',
	str_contains( $source, $expected_homeboy_review )
);
$assert(
	'stale Homeboy git changes command is absent',
	! str_contains( $source, $stale_homeboy_git )
);

if ( ! empty( $failures ) ) {
	echo "\nFAIL: " . count( $failures ) . " assertion(s)\n";
	foreach ( $failures as $f ) {
		echo "  - {$f}\n";
	}
	exit( 1 );
}

echo "\nOK\n";
exit( 0 );
