<?php
/**
 * Pure-PHP smoke test for the AGENTS.md compose marker.
 *
 * Run: php tests/smoke-agents-md-marker.php
 *
 * Keeps the generated AGENTS.md marker aligned with the current memory
 * compose command surface.
 */

declare( strict_types=1 );

$failures = array();
$assert   = function ( string $label, bool $cond ) use ( &$failures ): void {
    if ($cond ) {
        echo "  PASS {$label}\n";
        return;
    }

    $failures[] = $label;
    echo "  FAIL {$label}\n";
};

echo "AGENTS.md compose marker -- smoke\n";

$plugin_file = __DIR__ . '/../data-machine-code.php';
$class_file  = __DIR__ . '/../inc/Runtime/AgentsMdSections.php';
$entrypoint  = file_get_contents($plugin_file);
$source      = file_get_contents($class_file);

$assert('plugin source is readable', is_string($entrypoint) && '' !== $entrypoint);
$assert('AGENTS.md section source is readable', is_string($source) && '' !== $source);

if (! is_string($source) ) {
    $source = '';
}
if (! is_string($entrypoint) ) {
    $entrypoint = '';
}

$expected_marker            = '<!-- regenerated by: {$wp} datamachine memory compose AGENTS.md -->';
$expected_generated_at      = '<!-- generated at: {$generated_at} -->';
$expected_description       = 'Regenerate via: wp datamachine memory compose AGENTS.md';
$stale_marker               = 'datamachine agent compose AGENTS.md';
$expected_memory_agent_note = 'On multi-agent installs, pass `--agent=<slug>` to memory commands when auto-resolution is ambiguous.';
$expected_agent_cli         = 'datamachine agent list|create|access|token|installed|install|diff';
$stale_agent_cli            = 'datamachine agents list|create|access|tokens';
$expected_workspace_cli     = 'datamachine-code workspace adopt|clone|list|show|path|hygiene|remove|worktree';
$expected_worktree_cli      = 'datamachine-code workspace worktree add|list|remove|prune|cleanup|cleanup-artifacts|reconcile-metadata|refresh-context|finalize|mark-cleanup-eligible';
$expected_gitsync_cli       = 'gitsync bind|list|status|pull|submit|push|policy|unbind';
$expected_homeboy_git       = 'homeboy changes | status';
$expected_homeboy_path      = '--path <checkout>';
$expected_homeboy_trace     = 'homeboy trace';
$expected_homeboy_review    = 'homeboy review --changed-since --report=pr-comment';
$stale_homeboy_git          = 'homeboy git changes';
$expected_inventory_time    = 'Generated {$generated_at} from cloned repos';
$expected_inventory_truth   = 'workspace list` is the source of truth';
$expected_inventory_refresh = 'datamachine memory compose AGENTS.md{$agent_suffix}';
$expected_abilities_note    = 'does not currently register a WP-CLI abilities discovery command';
$stale_abilities_cli        = 'help abilities';

$assert(
    'auto-generated marker uses memory compose command',
    str_contains($source, $expected_marker)
);
$assert(
    'auto-generated marker includes generated timestamp',
    str_contains($source, $expected_generated_at)
);
$assert(
    'MemoryFileRegistry description uses memory compose command',
    str_contains($source, $expected_description)
);
$assert(
    'stale agent compose command is absent',
    ! str_contains($source, $stale_marker)
);
$assert(
    'agent CLI guidance uses current singular command surface',
    str_contains($source, $expected_agent_cli)
);
$assert(
    'memory guidance covers explicit agent slug on ambiguous installs',
    str_contains($source, $expected_memory_agent_note)
);
$assert(
    'stale plural agent token guidance is absent',
    ! str_contains($source, $stale_agent_cli)
);
$assert(
    'workspace lifecycle guidance includes current command family',
    str_contains($source, $expected_workspace_cli)
);
$assert(
    'worktree guidance includes current maintenance surfaces',
    str_contains($source, $expected_worktree_cli)
);
$assert(
    'workspace inventory renders generation time',
    str_contains($source, $expected_inventory_time)
);
$assert(
    'workspace inventory names workspace list as source of truth',
    str_contains($source, $expected_inventory_truth)
);
$assert(
    'workspace inventory includes memory compose refresh command',
    str_contains($source, $expected_inventory_refresh)
);
$assert(
    'abilities guidance avoids missing discovery command',
    str_contains($source, $expected_abilities_note) && ! str_contains($source, $stale_abilities_cli)
);
$assert(
    'GitSync guidance distinguishes compact sync family',
    str_contains($source, $expected_gitsync_cli)
);
$assert(
    'Homeboy guidance uses top-level changes command',
    str_contains($source, $expected_homeboy_git)
);
$assert(
    'Homeboy guidance covers --path checkout override',
    str_contains($source, $expected_homeboy_path)
);
$assert(
    'Homeboy guidance includes trace surface',
    str_contains($source, $expected_homeboy_trace)
);
$assert(
    'Homeboy guidance includes PR-style review loop',
    str_contains($source, $expected_homeboy_review)
);
$assert(
    'stale Homeboy git changes command is absent',
    ! str_contains($source, $stale_homeboy_git)
);
$assert(
    'plugin entrypoint delegates AGENTS.md section registration',
    str_contains($entrypoint, 'DataMachineCode\\Runtime\\AgentsMdSections')
);
$assert(
    'plugin entrypoint no longer contains AGENTS.md heredoc sections',
    ! str_contains($entrypoint, $expected_agent_cli) && ! str_contains($entrypoint, $expected_homeboy_review)
);

if (! empty($failures) ) {
    echo "\nFAIL: " . count($failures) . " assertion(s)\n";
    foreach ( $failures as $f ) {
        echo "  - {$f}\n";
    }
    exit(1);
}

echo "\nOK\n";
exit(0);
