<?php
/**
 * Smoke coverage for canonical runner workspace publication.
 *
 * Run: php tests/smoke-runner-workspace-publication.php
 */

declare( strict_types=1 );

namespace {
	if ( ! defined('ABSPATH') ) {
		define('ABSPATH', __DIR__ . '/');
	}

	if ( ! class_exists('WP_Error') ) {
		class WP_Error {
			private string $code;
			private string $message;
			private mixed $data;

			public function __construct( string $code = '', string $message = '', mixed $data = array() ) {
				$this->code    = $code;
				$this->message = $message;
				$this->data    = $data;
			}

			public function get_error_code(): string {
				return $this->code;
			}

			public function get_error_message(): string {
				return $this->message;
			}

			public function get_error_data(): mixed {
				return $this->data;
			}
		}
	}

	function is_wp_error( mixed $thing ): bool {
		return $thing instanceof WP_Error;
	}

	function wp_json_encode( mixed $data, int $flags = 0 ): string|false {
		return json_encode($data, $flags);
	}
}

namespace DataMachineCode\Abilities {
	class WorkspaceAbilities {
		public static array $calls = array();
		public static array $status = array(
			'success' => true,
			'backend' => 'github_api',
			'name'    => 'docs-agent@runner-docs',
			'branch'  => 'runner/docs',
			'dirty'   => 2,
			'files'   => array( 'docs/index.md', 'docs/setup.md' ),
		);

		public static function gitStatus( array $input ): array|\WP_Error {
			self::$calls[] = array( 'gitStatus', $input );
			return self::$status;
		}

		public static function gitAdd( array $input ): array|\WP_Error {
			self::$calls[] = array( 'gitAdd', $input );
			return array( 'success' => true, 'backend' => 'github_api', 'paths' => $input['paths'] ?? array() );
		}

		public static function gitCommit( array $input ): array|\WP_Error {
			self::$calls[] = array( 'gitCommit', $input );
			return array( 'success' => true, 'backend' => 'github_api', 'branch' => 'runner/docs', 'commit' => 'abcdef1234567890' );
		}

		public static function gitPush( array $input ): array|\WP_Error {
			self::$calls[] = array( 'gitPush', $input );
			return array(
				'success'     => true,
				'backend'     => 'github_api',
				'remote'      => 'origin',
				'branch'      => $input['branch'] ?? '',
				'github_repo' => 'Automattic/build-with-wordpress',
				'html_url'    => 'https://github.com/Automattic/build-with-wordpress/tree/runner%2Fdocs',
			);
		}
	}

	class GitHubAbilities {
		public static array $calls = array();
		public static bool $reuse = true;

		public static function createPullRequest( array $input ): array|\WP_Error {
			self::$calls[] = $input;
			return array(
				'success'     => true,
				'repo'        => $input['repo'],
				'number'      => 42,
				'pull_number' => 42,
				'html_url'    => 'https://github.com/Automattic/build-with-wordpress/pull/42',
				'reused'      => self::$reuse,
			);
		}
	}
}

namespace {
	include __DIR__ . '/../inc/Workspace/RunnerWorkspacePublisher.php';

	use DataMachineCode\Abilities\GitHubAbilities;
	use DataMachineCode\Abilities\WorkspaceAbilities;
	use DataMachineCode\Workspace\RunnerWorkspacePublisher;

	$failures = 0;
	$total    = 0;

	$assert = function ( string $message, bool $condition ) use ( &$failures, &$total ): void {
		$total++;
		if ( $condition ) {
			echo "  ✓ {$message}\n";
			return;
		}

		$failures++;
		echo "  ✗ {$message}\n";
	};

	echo "Runner workspace publication smoke\n";

	$publisher = new RunnerWorkspacePublisher();
	$result    = $publisher->publish(
		array(
			'workspace_handle'      => 'docs-agent@runner-docs',
			'target_repo'           => 'Automattic/build-with-wordpress',
			'base'                  => 'main',
			'head'                  => 'Automattic:runner/docs',
			'commit_message'        => 'docs: add developer setup guide',
			'pr_title'              => 'Add developer setup guide',
			'pr_body'               => 'Generated by runner.',
			'labels'                => array( 'docs', 'runner-owned' ),
			'draft'                 => true,
			'maintainer_can_modify' => false,
			'evidence_context'      => array( 'run_id' => '27345630013', 'artifact' => 'workspace-diff' ),
		)
	);

	$assert('publication succeeds', is_array($result) && true === ( $result['success'] ?? false ));
	$assert('remote backend is preserved', 'github_api' === ( $result['workspace']['backend'] ?? null ));
	$assert('commit metadata is typed', 'abcdef1234567890' === ( $result['commit']['sha'] ?? null ));
	$assert('PR metadata includes number', 42 === ( $result['pull_request']['number'] ?? null ));
	$assert('existing PR reuse state is preserved', true === ( $result['pull_request']['reused'] ?? null ));
	$assert('opened state is inverse of reuse', false === ( $result['pull_request']['opened'] ?? null ));
	$assert('push uses branch stripped from owner-qualified head', 'runner/docs' === ( WorkspaceAbilities::$calls[3][1]['branch'] ?? null ));
	$assert('PR uses owner-qualified head', 'Automattic:runner/docs' === ( GitHubAbilities::$calls[0]['head'] ?? null ));
	$assert('PR body includes evidence context', str_contains((string) ( GitHubAbilities::$calls[0]['body'] ?? '' ), '27345630013'));
	$assert('labels are forwarded to PR creation', array( 'docs', 'runner-owned' ) === ( GitHubAbilities::$calls[0]['labels'] ?? array() ));

	$ability_source = file_get_contents(__DIR__ . '/../inc/Abilities/WorkspaceAbilities.php');
	$tool_source    = file_get_contents(__DIR__ . '/../inc/Tools/WorkspaceTools.php');
	$github_source  = file_get_contents(__DIR__ . '/../inc/Abilities/GitHubAbilities.php');
	$assert('canonical ability is registered', false !== strpos((string) $ability_source, 'datamachine-code/publish-runner-workspace'));
	$assert('tool projection exposes canonical ability', false !== strpos((string) $tool_source, 'workspace_publish_runner'));
	$assert('existing workspace push ability remains registered', false !== strpos((string) $ability_source, 'datamachine-code/workspace-git-push'));
	$assert('existing GitHub PR ability remains registered', false !== strpos((string) $github_source, 'datamachine-code/create-github-pull-request'));

	$missing = $publisher->publish(array( 'target_repo' => 'Extra-Chill/example' ));
	$assert('missing handle returns typed failure', $missing instanceof WP_Error && 'runner_workspace_publish_missing_handle' === $missing->get_error_code());

	if ( $failures > 0 ) {
		echo "\n{$failures} of {$total} assertions failed.\n";
		exit(1);
	}

	echo "\nAll {$total} runner publication assertions passed.\n";
}
