<?php
/**
 * Pure-PHP smoke test for the AGENTS.md compose marker.
 *
 * Run: php tests/smoke-agents-md-marker.php
 *
 * Keeps the generated AGENTS.md marker aligned with the current memory
 * compose command surface.
 */

declare( strict_types=1 );

$failures = array();
$assert   = function ( string $label, bool $cond ) use ( &$failures ): void {
    if ($cond ) {
        echo "  PASS {$label}\n";
        return;
    }

    $failures[] = $label;
    echo "  FAIL {$label}\n";
};

echo "AGENTS.md compose marker -- smoke\n";

$plugin_file = __DIR__ . '/../data-machine-code.php';
$class_file  = __DIR__ . '/../inc/Runtime/AgentsMdSections.php';
$entrypoint  = file_get_contents($plugin_file);
$source      = file_get_contents($class_file);

$assert('plugin source is readable', is_string($entrypoint) && '' !== $entrypoint);
$assert('AGENTS.md section source is readable', is_string($source) && '' !== $source);

if (! is_string($source) ) {
    $source = '';
}
if (! is_string($entrypoint) ) {
    $entrypoint = '';
}

$expected_marker            = '<!-- regenerated by: {$wp} datamachine memory compose AGENTS.md -->';
$expected_generated_at      = '<!-- generated at: {$generated_at} -->';
$expected_description       = 'Regenerate via: wp datamachine memory compose AGENTS.md';
$stale_marker               = 'datamachine agent compose AGENTS.md';
$expected_memory_agent_note = 'On multi-agent installs, pass `--agent=<slug>` to memory commands when auto-resolution is ambiguous.';
$expected_agent_cli         = 'datamachine agent list|create|access|token|installed|install|diff';
$stale_agent_cli            = 'datamachine agents list|create|access|tokens';
// Workspace / GitHub / GitSync subcommand lists are now generated from the
// command classes via CommandIntrospector (see #671) instead of hardcoded
// pipe-lists, so the source asserts on the generation wiring + interpolation
// tokens rather than a frozen string. The actual produced surface is exercised
// against the real command classes further down.
$expected_workspace_token   = 'datamachine-code workspace {$workspace_subcmds}';
$expected_github_token       = 'datamachine-code github {$github_subcmds}';
$expected_gitsync_token      = 'datamachine-code gitsync {$gitsync_subcmds}';
$expected_introspect_wiring  = 'CommandIntrospector::pipe_list(';
$stale_hardcoded_workspace   = 'workspace adopt|clone|list|show|path|hygiene|remove|worktree';
$expected_worktree_cli      = 'datamachine-code workspace worktree add|list|remove|prune|cleanup|cleanup-artifacts|reconcile-metadata|refresh-context|finalize|mark-cleanup-eligible';
$expected_inventory_time    = 'Generated {$generated_at} from cloned repos';
$expected_inventory_truth   = 'workspace list` is the source of truth';
$expected_inventory_refresh = 'datamachine memory compose AGENTS.md{$agent_suffix}';
$expected_abilities_note    = 'does not currently register a WP-CLI abilities discovery command';
$stale_abilities_cli        = 'help abilities';
$expected_section_owner     = "'owner'       => 'data-machine-code'";
$expected_snapshot_fresh    = "'freshness'   => 'snapshot'";
$expected_static_fresh      = "'freshness'   => 'static'";
$expected_generated_fresh   = "'freshness'   => 'generated'";
$expected_multisite_cond    = "'conditions'  => 'Only registered on multisite installs.'";

$assert(
    'auto-generated marker uses memory compose command',
    str_contains($source, $expected_marker)
);
$assert(
    'auto-generated marker includes generated timestamp',
    str_contains($source, $expected_generated_at)
);
$assert(
    'MemoryFileRegistry description uses memory compose command',
    str_contains($source, $expected_description)
);
$assert(
    'stale agent compose command is absent',
    ! str_contains($source, $stale_marker)
);
$assert(
    'agent CLI guidance uses current singular command surface',
    str_contains($source, $expected_agent_cli)
);
$assert(
    'memory guidance covers explicit agent slug on ambiguous installs',
    str_contains($source, $expected_memory_agent_note)
);
$assert(
    'stale plural agent token guidance is absent',
    ! str_contains($source, $stale_agent_cli)
);
$assert(
    'workspace guidance is generated from the command class, not hardcoded',
    str_contains($source, $expected_workspace_token) && str_contains($source, $expected_introspect_wiring)
);
$assert(
    'stale hardcoded workspace pipe-list is gone (#671)',
    ! str_contains($source, $stale_hardcoded_workspace)
);
$assert(
    'GitHub guidance is generated from the command class',
    str_contains($source, $expected_github_token)
);
$assert(
    'worktree guidance includes current maintenance surfaces',
    str_contains($source, $expected_worktree_cli)
);
$assert(
    'workspace inventory renders generation time',
    str_contains($source, $expected_inventory_time)
);
$assert(
    'workspace inventory names workspace list as source of truth',
    str_contains($source, $expected_inventory_truth)
);
$assert(
    'workspace inventory includes memory compose refresh command',
    str_contains($source, $expected_inventory_refresh)
);
$assert(
    'abilities guidance avoids missing discovery command',
    str_contains($source, $expected_abilities_note) && ! str_contains($source, $stale_abilities_cli)
);
$assert(
    'GitSync guidance is generated from the command class',
    str_contains($source, $expected_gitsync_token)
);
$assert(
    'AGENTS.md sections declare Data Machine Code ownership',
    6 === substr_count($source, $expected_section_owner)
);
$assert(
    'AGENTS.md sections declare generated freshness for compose marker',
    str_contains($source, $expected_generated_fresh)
);
$assert(
    'AGENTS.md sections declare snapshot freshness for dynamic workspace guidance',
    2 === substr_count($source, $expected_snapshot_fresh)
);
$assert(
    'AGENTS.md sections declare static freshness for stable guidance',
    3 === substr_count($source, $expected_static_fresh)
);
$assert(
    'multisite section documents its registration condition',
    str_contains($source, $expected_multisite_cond)
);
$assert(
    'plugin entrypoint delegates AGENTS.md section registration',
    str_contains($entrypoint, 'DataMachineCode\\Runtime\\AgentsMdSections')
);
$assert(
    'plugin entrypoint no longer contains AGENTS.md heredoc sections',
    ! str_contains($entrypoint, $expected_agent_cli)
);

/*
 * Exercise the reflection introspector against the real command classes in a
 * non-WP-CLI context. This proves the workspace file-I/O surface that #671 was
 * about (read/write/grep/edit/git/patch/ls) is actually produced, and that the
 * helper runs without the WP_CLI runner being present.
 */
echo "\nCommandIntrospector against real command classes:\n";

if (! defined('ABSPATH') ) {
    define('ABSPATH', __DIR__ . '/');
}
if (! class_exists('WP_CLI') ) {
    eval('class WP_CLI {}');
}
if (! class_exists('DataMachine\\Cli\\BaseCommand') ) {
    eval('namespace DataMachine\\Cli; class BaseCommand {}');
}

require_once __DIR__ . '/../inc/Runtime/CommandIntrospector.php';
require_once __DIR__ . '/../inc/Cli/Commands/WorkspaceCommand.php';
require_once __DIR__ . '/../inc/Cli/Commands/GitHubCommand.php';
require_once __DIR__ . '/../inc/Cli/Commands/GitSyncCommand.php';

$workspace_subs = \DataMachineCode\Runtime\CommandIntrospector::subcommand_names('\\DataMachineCode\\Cli\\Commands\\WorkspaceCommand');
$github_subs    = \DataMachineCode\Runtime\CommandIntrospector::subcommand_names('\\DataMachineCode\\Cli\\Commands\\GitHubCommand');
$gitsync_subs   = \DataMachineCode\Runtime\CommandIntrospector::subcommand_names('\\DataMachineCode\\Cli\\Commands\\GitSyncCommand');

$required_file_io = array( 'read', 'write', 'grep', 'edit', 'git', 'patch', 'ls' );
$missing_file_io  = array_values(array_diff($required_file_io, $workspace_subs));

$assert(
    'workspace reflection surfaces the file-I/O subcommands omitted by #671',
    empty($missing_file_io)
);
if (! empty($missing_file_io) ) {
    echo '    missing: ' . implode(', ', $missing_file_io) . "\n";
}
$assert(
    'workspace reflection still surfaces lifecycle subcommands',
    empty(array_diff(array( 'clone', 'adopt', 'worktree', 'hygiene' ), $workspace_subs))
);
$assert(
    'github reflection surfaces issue + PR subcommands',
    empty(array_diff(array( 'issues', 'pulls', 'review-flow', 'comment' ), $github_subs))
);
$assert(
    'gitsync reflection surfaces bind/submit/push subcommands',
    empty(array_diff(array( 'bind', 'submit', 'push', 'policy' ), $gitsync_subs))
);

if (! empty($failures) ) {
    echo "\nFAIL: " . count($failures) . " assertion(s)\n";
    foreach ( $failures as $f ) {
        echo "  - {$f}\n";
    }
    exit(1);
}

echo "\nOK\n";
exit(0);
