<?php
/**
 * AGENTS.md section registration for Data Machine Code.
 *
 * @package DataMachineCode\Runtime
 */

namespace DataMachineCode\Runtime;

use DataMachineCode\Workspace\Workspace;

defined('ABSPATH') || exit;

final class AgentsMdSections {

	/**
	 * Register AGENTS.md as a composable memory file and add DMC-owned sections.
	 */
	public static function register(): void {
		if ( ! function_exists('datamachine_agents_md_enabled') || ! datamachine_agents_md_enabled() ) {
			return;
		}

		if ( ! class_exists('\DataMachine\Engine\AI\MemoryFileRegistry') ) {
			return;
		}

		$registry_class = '\DataMachine\Engine\AI\MemoryFileRegistry';
		$register       = array( $registry_class, 'register' );
		/** @var callable $register */

		call_user_func(
			$register,
			'AGENTS.md', 5, array(
				'layer'           => defined($registry_class . '::LAYER_SHARED') ? constant($registry_class . '::LAYER_SHARED') : 'shared',
				'protected'       => true,
				'composable'      => true,
				'convention_path' => 'AGENTS.md',
				'label'           => 'Agent Instructions',
				'description'     => 'Auto-generated from registered sections. Regenerate via: wp datamachine memory compose AGENTS.md',
			)
		);

		if ( ! class_exists('\DataMachine\Engine\AI\SectionRegistry') ) {
			return;
		}

		$wp = self::resolve_wp_cli_cmd();

		self::register_auto_generated_marker($wp);
		self::register_datamachine_section($wp);
		self::register_multisite_section($wp);
	}

	private static function register_auto_generated_marker( string $wp ): void {
		self::register_section(
			'AGENTS.md', 'auto-generated-marker', 0, function () use ( $wp ) {
				$generated_at = gmdate('c');
				return <<<MD
<!-- regenerated by: {$wp} datamachine memory compose AGENTS.md -->
<!-- generated at: {$generated_at} -->
<!-- edit registered sections in their owning plugins, not this file -->
MD;
			}, array(
				'label'       => 'Auto-generated marker',
				'description' => 'HTML-comment header signalling that AGENTS.md is composed from registered sections.',
				'owner'       => 'data-machine-code',
				'freshness'   => 'generated',
				'conditions'  => 'Always registered when Data Machine Code and composable memory section registration are available.',
			)
		);
	}

	private static function register_datamachine_section( string $wp ): void {
		self::register_section(
			'AGENTS.md', 'datamachine-code', 20, function () use ( $wp ) {
				$workspace_path           = self::resolve_workspace_path();
				$workspace_policy_intro   = self::render_workspace_policy_intro($workspace_path);
				$workspace_policy_section = self::render_workspace_policy_section($workspace_path, $wp);

				return <<<MD
## Data Machine Code

Data Machine Code provides repository, primary-checkout, worktree, and GitHub workspace management. {$workspace_policy_intro}

**Default routing**
- Inspect workspace state: `{$wp} datamachine-code workspace list`, `{$wp} datamachine-code workspace show <repo>`, or `{$wp} datamachine-code workspace hygiene`
- Create isolated work: `{$wp} datamachine-code workspace worktree add <repo> <branch> --from=origin/<base>`
- Record PR/final state: `{$wp} datamachine-code workspace worktree finalize <repo@slug> --pr=<url>`. Creators of `remove_on_success` disposable worktrees must terminally finalize their own run with `--owner-terminal-outcome=success`; this is the explicit handoff to cleanup after clean/pushed/non-live safety checks.
- Refresh an authoritative primary: `{$wp} datamachine-code workspace git pull <repo> --allow-primary-refresh`
- Inspect or manage GitHub state: `{$wp} datamachine-code github --help`
- Edit inside a local worktree with native file tools and raw `git`; routing local file I/O through workspace abilities is ceremony, not safety.

**Safety**
{$workspace_policy_section}

**Discovery**
Use `{$wp} datamachine-code workspace --help` and `{$wp} datamachine-code workspace worktree --help` for the live lifecycle contract. Query `workspace list`, `workspace show`, or `workspace hygiene` for current state instead of relying on an embedded inventory snapshot.

**WordPress recovery**
If WordPress or its database cannot boot, use the installed plugin's `bin/dmc-worktree-provider inventory <workspace-root> --limit=50` or `bin/dmc-worktree-provider show <workspace-root> <handle> --format=json`. These standalone operations report bounded live filesystem/Git observations only; restore WordPress/database access and return to `{$wp} datamachine-code workspace list` or `workspace show` for authoritative lifecycle metadata.
MD;
			}, array(
				'label'       => 'Data Machine Code',
				'description' => 'Data Machine Code workspace lifecycle, GitHub, and safety guidance.',
				'owner'       => 'data-machine-code',
				'freshness'   => 'snapshot',
				'conditions'  => 'Always registered when Data Machine Code and composable memory section registration are available.',
			)
		);
	}

	private static function render_workspace_policy_intro( string $workspace_path ): string {
		$default = "When using Data Machine Code to manage code changes, work in a Data Machine Code worktree. The controller workspace root is `{$workspace_path}`. ";

		/**
		 * Filters the site-owned workspace policy sentence rendered before DMC command facts.
		 *
		 * @param string $default        Default policy markdown.
		 * @param string $workspace_path Resolved DMC workspace root.
		 */
		/** @var mixed $filtered */
		$filtered = apply_filters('datamachine_code_workspace_policy_intro', $default, $workspace_path);
		if ( ! is_string($filtered) ) {
			return $default;
		}

		return $filtered;
	}

	private static function render_workspace_policy_section( string $workspace_path, string $wp ): string {
		$default = <<<MD
- **Primary freshness:** before using a primary checkout for investigation or verification, inspect `{$wp} datamachine-code workspace show <repo>` or `{$wp} datamachine-code workspace hygiene`. If the primary is stale, run `{$wp} datamachine-code workspace git pull <repo> --allow-primary-refresh` or create a worktree from `origin/<base>`. A clean diverged default branch is preserved in a deterministic managed recovery worktree before the primary is refreshed; review its typed recovery evidence and reconcile that branch. Stale primary reads require an explicit `--allow-stale-primary` opt-in. Do not clone a second top-level primary for the same remote just to get fresh code.
- **Primary is read-only.** Never edit `<workspace>/<repo>` (no `@slug`). Safe primary refresh uses `--allow-primary-refresh`; primary commit, push, reset, and rebase require the stronger `--allow-dangerous-primary-mutation` approval. The primary tracks the deployed branch — operate on a worktree.
MD;

		/**
		 * Filters site-owned workspace policy guidance rendered in AGENTS.md.
		 *
		 * Data Machine Code owns the workspace command facts above. Callers own
		 * local policy, such as primary checkout mutability and read-only source
		 * directory rules. Return an empty string to omit the policy block.
		 *
		 * @param string $default        Default policy markdown.
		 * @param string $workspace_path Resolved DMC workspace root.
		 * @param string $wp             WP-CLI command prefix.
		 */
		/** @var mixed $filtered */
		$filtered = apply_filters('datamachine_code_workspace_policy_section', $default, $workspace_path, $wp);
		if ( ! is_string($filtered) ) {
			return $default;
		}

		return trim($filtered);
	}

	private static function register_multisite_section( string $wp ): void {
		if ( ! is_multisite() ) {
			return;
		}

		self::register_section(
			'AGENTS.md', 'multisite', 40, function () use ( $wp ) {
				return <<<MD
## Multisite

This is a WordPress multisite. Use `--url` to target specific sites:
```
{$wp} --url=site.example.com <command>
```
Without `--url`, commands default to the main site.
MD;
			}, array(
				'label'       => 'Multisite',
				'description' => 'Multisite-specific WP-CLI guidance.',
				'owner'       => 'data-machine-code',
				'freshness'   => 'static',
				'conditions'  => 'Only registered on multisite installs.',
			)
		);
	}

	/**
	 * Resolve the WP-CLI command prefix for the current environment.
	 */
	private static function resolve_wp_cli_cmd(): string {
		$parts = array( 'wp' );

		if ( function_exists('posix_geteuid') && 0 === posix_geteuid() ) {
			$parts[] = '--allow-root';
		}

		$abspath = rtrim(ABSPATH, '/');
		if ( '/var/www/html' !== $abspath ) {
			$parts[] = '--path=' . $abspath;
		}

		return apply_filters('datamachine_wp_cli_cmd', implode(' ', $parts));
	}

	/**
	 * Register an AGENTS.md section through the optional Data Machine registry.
	 */
	private static function register_section( string $file, string $section, int $priority, callable $callback, array $metadata ): void {
		$registry_class = '\DataMachine\Engine\AI\SectionRegistry';
		$register       = array( $registry_class, 'register' );
		/** @var callable $register */

		call_user_func($register, $file, $section, $priority, $callback, $metadata);
	}

	private static function resolve_workspace_path(): string {
		if ( class_exists(Workspace::class) ) {
			$workspace_path = ( new Workspace() )->get_path();
			if ( '' !== $workspace_path ) {
				return $workspace_path;
			}
		}

		return 'unavailable; run datamachine-code workspace path to diagnose';
	}
}
