<?php
/**
 * AGENTS.md section registration for Data Machine Code.
 *
 * @package DataMachineCode\Runtime
 */

namespace DataMachineCode\Runtime;

use DataMachineCode\Workspace\Workspace;

defined('ABSPATH') || exit;

final class AgentsMdSections {

	/**
	 * Register AGENTS.md as a composable memory file and add DMC-owned sections.
	 */
	public static function register(): void {
		if ( ! class_exists('\DataMachine\Engine\AI\MemoryFileRegistry') ) {
			return;
		}

		$registry_class = '\DataMachine\Engine\AI\MemoryFileRegistry';
		if ( ! method_exists($registry_class, 'register') ) {
			return;
		}

		$registry_class::register(
			'AGENTS.md', 5, array(
				'layer'           => defined($registry_class . '::LAYER_SHARED') ? constant($registry_class . '::LAYER_SHARED') : 'shared',
				'protected'       => true,
				'composable'      => true,
				'convention_path' => 'AGENTS.md',
				'label'           => 'Agent Instructions',
				'description'     => 'Auto-generated from registered sections. Regenerate via: wp datamachine memory compose AGENTS.md',
			)
		);

		if ( ! class_exists('\DataMachine\Engine\AI\SectionRegistry') ) {
			return;
		}

		$wp = self::resolve_wp_cli_cmd();

		self::register_auto_generated_marker($wp);
		self::register_datamachine_section($wp);
		self::register_workspace_inventory_section($wp);
		self::register_abilities_section();
		self::register_wordpress_source_section();
		self::register_multisite_section($wp);
	}

	/**
	 * Register workspace change hooks that invalidate composable AGENTS.md.
	 */
	public static function register_invalidation_hooks( array $hooks ): array {
		$hooks[] = 'datamachine_code_workspace_changed';
		return $hooks;
	}

	private static function register_auto_generated_marker( string $wp ): void {
		\DataMachine\Engine\AI\SectionRegistry::register(
			'AGENTS.md', 'auto-generated-marker', 0, function () use ( $wp ) {
				$generated_at = gmdate('c');
				return <<<MD
<!-- regenerated by: {$wp} datamachine memory compose AGENTS.md -->
<!-- generated at: {$generated_at} -->
<!-- edit registered sections in their owning plugins, not this file -->
MD;
			}, array(
				'label'       => 'Auto-generated marker',
				'description' => 'HTML-comment header signalling that AGENTS.md is composed from registered sections.',
				'owner'       => 'data-machine-code',
				'freshness'   => 'generated',
				'conditions'  => 'Always registered when Data Machine Code and composable memory section registration are available.',
			)
		);
	}

	private static function register_datamachine_section( string $wp ): void {
		\DataMachine\Engine\AI\SectionRegistry::register(
			'AGENTS.md', 'datamachine', 10, function () use ( $wp ) {
				$workspace_path = self::resolve_workspace_path();
				$agent_slug     = self::resolve_agent_slug();
				$agent_suffix   = '' !== $agent_slug ? ' --agent=' . $agent_slug : '';
				$agent_note     = '' !== $agent_slug
					? "On this site, scope memory commands with `--agent={$agent_slug}` when reading, writing, searching, or composing agent memory."
					: 'On multi-agent installs, pass `--agent=<slug>` to memory commands when auto-resolution is ambiguous.';

				// Generate DMC's own command surface from reflection so the lists
				// never drift from the registered truth (see #671). The fallback
				// pipe-lists are only used if a command class is somehow
				// unavailable in this compose context.
				$workspace_subcmds = CommandIntrospector::pipe_list(
					'\\DataMachineCode\\Cli\\Commands\\WorkspaceCommand',
					'adopt|clone|list|show|path|hygiene|remove|worktree|read|write|grep|edit|git|patch|ls'
				);
				$github_subcmds = CommandIntrospector::pipe_list(
					'\\DataMachineCode\\Cli\\Commands\\GitHubCommand',
					'issues|pulls|repos|status|view|close|review-flow|comment'
				);
				$gitsync_subcmds = CommandIntrospector::pipe_list(
					'\\DataMachineCode\\Cli\\Commands\\GitSyncCommand',
					'bind|list|status|pull|submit|push|policy|unbind'
				);

				return <<<MD
## Data Machine

Data Machine is your operating layer — memory, automation, and orchestration via WP-CLI.

Discover the full command surface: `{$wp} datamachine --help`. The groups below are the major command families — always run `--help` on any subcommand to see its options.

**Memory & Agents:** Persistent files across sessions plus agent identity management.
- Memory paths / read / write / search / compose: `{$wp} datamachine memory paths|read|write|search|compose{$agent_suffix}`
- Agent management: `{$wp} datamachine agent list|create|access|token|installed|install|diff` — identities, permissions, bearer tokens, portable bundles
- Update MEMORY.md when you learn something persistent — read it first, append new info.
- {$agent_note}

**Automation:** Self-scheduling workflows that run without human intervention.
- Flows: `{$wp} datamachine flow create|run|list` — scheduled or on-demand tasks
- Pipelines: `{$wp} datamachine pipeline create|list` — multi-step processing chains
- Jobs / pending actions: `{$wp} datamachine jobs list|retry|summary`, `{$wp} datamachine pending-actions` — monitor queued work and approval gates
- Drain due work: `{$wp} datamachine drain` — run due actions until empty or budgeted
- Discover available step types: `{$wp} datamachine step-types list`
- Discover available handlers: `{$wp} datamachine handlers list`
- Processed items (dedupe): `{$wp} datamachine processed-items`
- Retention policies: `{$wp} datamachine retention`

**Communication:** Chat sessions and email I/O.
- Chat: `{$wp} datamachine chat` — multi-turn agent conversations with tool calling
- Email: `{$wp} datamachine email` — IMAP read / SMTP reply (wired to the site's mail stack)

**Content ops:** Post-level and site-wide content tooling.
- Posts / taxonomy / blocks: `{$wp} datamachine post|taxonomy|block`
- SEO helpers: `{$wp} datamachine alt-text|meta-description|image|link|indexnow`
- Analytics & logs: `{$wp} datamachine analytics|logs`
- Settings & auth: `{$wp} datamachine settings|auth`
- External sites & handler tests: `{$wp} datamachine external|test`

**Code (data-machine-code):** All code changes happen in Data Machine Code worktrees under `{$workspace_path}`. DMC owns workspace lifecycle, evidence capture, GitHub workflow glue, and GitSync; file CRUD inside a worktree uses whatever tool is fastest.
- Workspace root: `{$workspace_path}`
- **Workspace:** `{$wp} datamachine-code workspace {$workspace_subcmds}` — lifecycle (clone/adopt/list/show/path/hygiene/remove/worktree), plus the file-I/O surface you work through inside a worktree (`read`, `write`, `grep`, `edit`, `patch`, `ls`, `git`). Keeps the on-disk registry consistent and enforces the `<repo>@<slug>` handle convention.
- **Worktrees:** `{$wp} datamachine-code workspace worktree add|list|remove|prune|cleanup|cleanup-artifacts|reconcile-metadata|refresh-context|finalize|mark-cleanup-eligible` — create isolated branches, refresh agent context, attach lifecycle metadata, and clean up safely.
- **GitHub:** `{$wp} datamachine-code github {$github_subcmds}` — list/read GitHub state, manage issues and PRs, install review flows, and comment on reviews.
- **Git sync:** `{$wp} datamachine-code gitsync {$gitsync_subcmds}` — bind site-owned directories to remotes; `submit` opens or updates the PR path, while `push` writes directly to the configured branch.
- **Editing inside a worktree:** any tool. Local agents on the same disk should use native file I/O and raw `git`; routing edits through workspace abilities is ceremony, not safety.
- **Workflow:** reuse the existing primary when one exists for the remote; otherwise `workspace clone <repo>` once → `worktree add <repo> <branch>` → edit files in the worktree with any tool → commit → push → PR.
- **Primary freshness:** before using a primary checkout for investigation or verification, inspect `workspace list|show|hygiene` freshness metadata. If the primary is stale, run `workspace git pull <repo> --allow-primary-mutation` or create the worktree from an explicit remote ref with `worktree add <repo> <branch> --from=origin/<base>`. Do not clone a second top-level primary for the same remote just to get fresh code.
- **Why worktrees:** parallel-session isolation on disk. Multiple agents cook features in the same repo without stepping on each other.
- **Primary is read-only.** Never edit `<workspace>/<repo>` (no `@slug`). Mutating ops on bare `<repo>` handles via the CLI require `--allow-primary-mutation`. The primary tracks the deployed branch — operate on a worktree.
- **Rule:** Never modify files under `wp-content/plugins/` or `wp-content/themes/` directly. Those paths are **read-only reference**. All code changes go through the workspace so they are tracked in git and reviewed via pull requests.

**System:** `{$wp} datamachine system health|prompts|run` — site health, prompt inspection, diagnostic runs.

Use `--help` on any command to discover options and subcommands.
MD;
			}, array(
				'label'       => 'Data Machine',
				'description' => 'Memory, automation, workspace, and system operations.',
				'owner'       => 'data-machine-code',
				'freshness'   => 'snapshot',
				'conditions'  => 'Always registered when Data Machine Code and composable memory section registration are available.',
			)
		);
	}

	private static function register_workspace_inventory_section( string $wp ): void {
		\DataMachine\Engine\AI\SectionRegistry::register(
			'AGENTS.md', 'workspace-inventory', 15, function () use ( $wp ) {
				return self::render_workspace_inventory_section($wp);
			}, array(
				'label'       => 'Workspace Inventory',
				'description' => 'Live snapshot of cloned repos + active worktrees in the workspace.',
				'owner'       => 'data-machine-code',
				'freshness'   => 'snapshot',
				'conditions'  => 'Registered when Data Machine Code is active; content is omitted when no workspace inventory is available.',
			)
		);
	}

	private static function register_abilities_section(): void {
		\DataMachine\Engine\AI\SectionRegistry::register(
			'AGENTS.md', 'abilities', 20, function () {
				return <<<'MD'
## Abilities

WordPress Abilities are the universal tool surface. Plugins register abilities that are automatically available via REST API, MCP, and chat.

Data Machine Code does not currently register a WP-CLI abilities discovery command. Use the active runtime tool listings exposed to MCP/chat/REST, and plugin-specific `--help` output, before assuming what's available.
MD;
			}, array(
				'label'       => 'Abilities',
				'description' => 'WordPress Abilities API discovery.',
				'owner'       => 'data-machine-code',
				'freshness'   => 'static',
				'conditions'  => 'Always registered when Data Machine Code and composable memory section registration are available.',
			)
		);
	}

	private static function register_wordpress_source_section(): void {
		\DataMachine\Engine\AI\SectionRegistry::register(
			'AGENTS.md', 'wordpress-source', 30, function () {
				return <<<'MD'
## WordPress Source (Read-Only Reference)

These directories are **read-only reference material** — grep and read them to understand code, but never edit them directly. All code changes go through the workspace (see Code above).

- `wp-content/plugins/` — plugin source (read-only)
- `wp-content/themes/` — theme source (read-only)
- `wp-includes/` — WordPress core (read-only)
MD;
			}, array(
				'label'       => 'WordPress Source',
				'description' => 'Pointers to WordPress source directories.',
				'owner'       => 'data-machine-code',
				'freshness'   => 'static',
				'conditions'  => 'Always registered when Data Machine Code and composable memory section registration are available.',
			)
		);
	}

	private static function register_multisite_section( string $wp ): void {
		if ( ! is_multisite() ) {
			return;
		}

		\DataMachine\Engine\AI\SectionRegistry::register(
			'AGENTS.md', 'multisite', 40, function () use ( $wp ) {
				return <<<MD
## Multisite

This is a WordPress multisite. Use `--url` to target specific sites:
```
{$wp} --url=site.example.com <command>
```
Without `--url`, commands default to the main site.
MD;
			}, array(
				'label'       => 'Multisite',
				'description' => 'Multisite-specific WP-CLI guidance.',
				'owner'       => 'data-machine-code',
				'freshness'   => 'static',
				'conditions'  => 'Only registered on multisite installs.',
			)
		);
	}

	/**
	 * Resolve the WP-CLI command prefix for the current environment.
	 */
	private static function resolve_wp_cli_cmd(): string {
		$parts = array( 'wp' );

		if ( function_exists('posix_geteuid') && 0 === posix_geteuid() ) {
			$parts[] = '--allow-root';
		}

		$abspath = rtrim(ABSPATH, '/');
		if ( '/var/www/html' !== $abspath ) {
			$parts[] = '--path=' . $abspath;
		}

		return apply_filters('datamachine_wp_cli_cmd', implode(' ', $parts));
	}

	private static function resolve_workspace_path(): string {
		if ( class_exists(Workspace::class) ) {
			$workspace_path = ( new Workspace() )->get_path();
			if ( '' !== $workspace_path ) {
				return $workspace_path;
			}
		}

		return 'unavailable; run datamachine-code workspace path to diagnose';
	}

	private static function resolve_agent_slug(): string {
		if ( class_exists('\DataMachine\Core\FilesRepository\DirectoryManager') ) {
			try {
				$directory_manager = new \DataMachine\Core\FilesRepository\DirectoryManager();
				$user_id           = method_exists($directory_manager, 'get_effective_user_id') ? (int) $directory_manager->get_effective_user_id(0) : 0;
				$agent_slug        = method_exists($directory_manager, 'resolve_agent_slug') ? (string) $directory_manager->resolve_agent_slug(array( 'user_id' => $user_id )) : '';

				if ( '' !== trim($agent_slug) ) {
					return trim($agent_slug);
				}
			} catch ( \Throwable $e ) {
				return '';
			}
		}

		return '';
	}

	private static function render_workspace_inventory_section( string $wp ): string {
		if ( ! class_exists(Workspace::class) ) {
			return '';
		}

		$workspace = new Workspace();
		$listing   = $workspace->list_repos();

		if ( is_wp_error($listing) || empty($listing['repos']) ) {
			return '';
		}

		$by_repo = array();
		foreach ( $listing['repos'] as $entry ) {
			if ( empty($entry['git']) ) {
				continue;
			}

			$repo = $entry['repo'] ?? $entry['name'] ?? '';
			if ( '' === $repo ) {
				continue;
			}

			if ( ! isset($by_repo[ $repo ]) ) {
				$by_repo[ $repo ] = array(
					'primary'   => null,
					'worktrees' => array(),
				);
			}

			if ( ! empty($entry['is_worktree']) ) {
				$by_repo[ $repo ]['worktrees'][] = $entry;
			} else {
				$by_repo[ $repo ]['primary'] = $entry;
			}
		}

		if ( empty($by_repo) ) {
			return '';
		}

		ksort($by_repo, SORT_NATURAL | SORT_FLAG_CASE);

		$mode = apply_filters('datamachine_code_workspace_inventory_mode', 'compact');
		if ( ! in_array($mode, array( 'compact', 'full' ), true) ) {
			$mode = 'compact';
		}

		$lines = array();
		foreach ( $by_repo as $repo => $bucket ) {
			$primary    = $bucket['primary'];
			$worktrees  = $bucket['worktrees'];
			$wt_count   = count($worktrees);
			$branch     = $primary['branch'] ?? null;
			$remote     = $primary['remote'] ?? null;
			$branch_str = ( null !== $branch && '' !== $branch ) ? sprintf(' (`%s`)', $branch) : '';

			if ( 'compact' === $mode ) {
				$suffix_parts   = array();
				$suffix_parts[] = sprintf('%d %s', $wt_count, 1 === $wt_count ? 'worktree' : 'worktrees');
				if ( null !== $remote && '' !== $remote ) {
					$suffix_parts[] = $remote;
				}
				$lines[] = sprintf('- **%s**%s — %s', $repo, $branch_str, implode(' · ', $suffix_parts));
				continue;
			}

			$header = sprintf('- **%s**%s', $repo, $branch_str);
			if ( null !== $remote && '' !== $remote ) {
				$header .= ' — ' . $remote;
			}
			$lines[] = $header;

			usort(
				$worktrees, function ( $a, $b ) {
					return strnatcasecmp( (string) ( $a['name'] ?? '' ), (string) ( $b['name'] ?? '' ) );
				}
			);
			foreach ( $worktrees as $wt ) {
				$slug      = $wt['branch_slug'] ?? '';
				$wt_branch = $wt['branch'] ?? null;
				$wt_label  = '' !== $slug ? sprintf('`%s`', $slug) : sprintf('`%s`', $wt['name'] ?? '?');
				if ( null !== $wt_branch && '' !== $wt_branch && $wt_branch !== $slug ) {
					$wt_label .= sprintf(' (`%s`)', $wt_branch);
				}
				$lines[] = '  - ' . $wt_label;
			}
		}

		$body           = implode("\n", $lines);
		$generated_at   = gmdate('c');
		$workspace_path = $listing['path'];
		$agent_slug     = self::resolve_agent_slug();
		$agent_suffix   = '' !== $agent_slug ? ' --agent=' . $agent_slug : '';

		return <<<MD
## Workspace Inventory

Generated {$generated_at} from cloned repos in `{$workspace_path}`. This section can be stale; `{$wp} datamachine-code workspace list` is the source of truth for current worktrees and branches.

Refresh this file with `{$wp} datamachine memory compose AGENTS.md{$agent_suffix}` after workspace changes if the inventory looks stale.

{$body}
MD;
	}
}
